//    MIT NON-AI License
//
//    Copyright (c) 2022-2025 Aleksei Kotelnikov(gudron2s@gmail.com)
//
//    Permission is hereby granted, free of charge, to any person obtaining a copy of the software and associated documentation files (the "Software"),
//    to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
//    and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions.
//
//    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
//
//    In addition, the following restrictions apply:
//
//    1. The Software and any modifications made to it may not be used for the purpose of training or improving machine learning algorithms,
//    including but not limited to artificial intelligence, natural language processing, or data mining. This condition applies to any derivatives,
//    modifications, or updates based on the Software code. Any usage of the Software in an AI-training dataset is considered a breach of this License.
//
//    2. The Software may not be included in any dataset used for training or improving machine learning algorithms,
//    including but not limited to artificial intelligence, natural language processing, or data mining.
//
//    3. Any person or organization found to be in violation of these restrictions will be subject to legal action and may be held liable
//    for any damages resulting from such use.
//
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
//    DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
//    OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: controller_api.proto

package controller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HdWalletControllerManagerApi_AddNewWallet_FullMethodName      = "/manager_api.HdWalletControllerManagerApi/AddNewWallet"
	HdWalletControllerManagerApi_ImportWallet_FullMethodName      = "/manager_api.HdWalletControllerManagerApi/ImportWallet"
	HdWalletControllerManagerApi_EnableWallet_FullMethodName      = "/manager_api.HdWalletControllerManagerApi/EnableWallet"
	HdWalletControllerManagerApi_GetWalletInfo_FullMethodName     = "/manager_api.HdWalletControllerManagerApi/GetWalletInfo"
	HdWalletControllerManagerApi_GetEnabledWallets_FullMethodName = "/manager_api.HdWalletControllerManagerApi/GetEnabledWallets"
	HdWalletControllerManagerApi_DisableWallet_FullMethodName     = "/manager_api.HdWalletControllerManagerApi/DisableWallet"
	HdWalletControllerManagerApi_DisableWallets_FullMethodName    = "/manager_api.HdWalletControllerManagerApi/DisableWallets"
	HdWalletControllerManagerApi_EnableWallets_FullMethodName     = "/manager_api.HdWalletControllerManagerApi/EnableWallets"
	HdWalletControllerManagerApi_GetAccount_FullMethodName        = "/manager_api.HdWalletControllerManagerApi/GetAccount"
)

// HdWalletControllerManagerApiClient is the client API for HdWalletControllerManagerApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HdWalletControllerManagerApiClient interface {
	AddNewWallet(ctx context.Context, in *AddNewWalletRequest, opts ...grpc.CallOption) (*AddNewWalletResponse, error)
	ImportWallet(ctx context.Context, in *ImportWalletRequest, opts ...grpc.CallOption) (*ImportWalletResponse, error)
	EnableWallet(ctx context.Context, in *EnableWalletRequest, opts ...grpc.CallOption) (*EnableWalletResponse, error)
	GetWalletInfo(ctx context.Context, in *GetWalletInfoRequest, opts ...grpc.CallOption) (*GetWalletInfoResponse, error)
	GetEnabledWallets(ctx context.Context, in *GetEnabledWalletsRequest, opts ...grpc.CallOption) (*GetEnabledWalletsResponse, error)
	DisableWallet(ctx context.Context, in *DisableWalletRequest, opts ...grpc.CallOption) (*DisableWalletResponse, error)
	DisableWallets(ctx context.Context, in *DisableWalletsRequest, opts ...grpc.CallOption) (*DisableWalletsResponse, error)
	EnableWallets(ctx context.Context, in *EnableWalletsRequest, opts ...grpc.CallOption) (*EnableWalletsResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
}

type hdWalletControllerManagerApiClient struct {
	cc grpc.ClientConnInterface
}

func NewHdWalletControllerManagerApiClient(cc grpc.ClientConnInterface) HdWalletControllerManagerApiClient {
	return &hdWalletControllerManagerApiClient{cc}
}

func (c *hdWalletControllerManagerApiClient) AddNewWallet(ctx context.Context, in *AddNewWalletRequest, opts ...grpc.CallOption) (*AddNewWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNewWalletResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_AddNewWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerManagerApiClient) ImportWallet(ctx context.Context, in *ImportWalletRequest, opts ...grpc.CallOption) (*ImportWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportWalletResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_ImportWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerManagerApiClient) EnableWallet(ctx context.Context, in *EnableWalletRequest, opts ...grpc.CallOption) (*EnableWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableWalletResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_EnableWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerManagerApiClient) GetWalletInfo(ctx context.Context, in *GetWalletInfoRequest, opts ...grpc.CallOption) (*GetWalletInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletInfoResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_GetWalletInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerManagerApiClient) GetEnabledWallets(ctx context.Context, in *GetEnabledWalletsRequest, opts ...grpc.CallOption) (*GetEnabledWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEnabledWalletsResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_GetEnabledWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerManagerApiClient) DisableWallet(ctx context.Context, in *DisableWalletRequest, opts ...grpc.CallOption) (*DisableWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableWalletResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_DisableWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerManagerApiClient) DisableWallets(ctx context.Context, in *DisableWalletsRequest, opts ...grpc.CallOption) (*DisableWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisableWalletsResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_DisableWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerManagerApiClient) EnableWallets(ctx context.Context, in *EnableWalletsRequest, opts ...grpc.CallOption) (*EnableWalletsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableWalletsResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_EnableWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerManagerApiClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerManagerApi_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HdWalletControllerManagerApiServer is the server API for HdWalletControllerManagerApi service.
// All implementations must embed UnimplementedHdWalletControllerManagerApiServer
// for forward compatibility.
type HdWalletControllerManagerApiServer interface {
	AddNewWallet(context.Context, *AddNewWalletRequest) (*AddNewWalletResponse, error)
	ImportWallet(context.Context, *ImportWalletRequest) (*ImportWalletResponse, error)
	EnableWallet(context.Context, *EnableWalletRequest) (*EnableWalletResponse, error)
	GetWalletInfo(context.Context, *GetWalletInfoRequest) (*GetWalletInfoResponse, error)
	GetEnabledWallets(context.Context, *GetEnabledWalletsRequest) (*GetEnabledWalletsResponse, error)
	DisableWallet(context.Context, *DisableWalletRequest) (*DisableWalletResponse, error)
	DisableWallets(context.Context, *DisableWalletsRequest) (*DisableWalletsResponse, error)
	EnableWallets(context.Context, *EnableWalletsRequest) (*EnableWalletsResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	mustEmbedUnimplementedHdWalletControllerManagerApiServer()
}

// UnimplementedHdWalletControllerManagerApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHdWalletControllerManagerApiServer struct{}

func (UnimplementedHdWalletControllerManagerApiServer) AddNewWallet(context.Context, *AddNewWalletRequest) (*AddNewWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewWallet not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) ImportWallet(context.Context, *ImportWalletRequest) (*ImportWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportWallet not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) EnableWallet(context.Context, *EnableWalletRequest) (*EnableWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableWallet not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) GetWalletInfo(context.Context, *GetWalletInfoRequest) (*GetWalletInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletInfo not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) GetEnabledWallets(context.Context, *GetEnabledWalletsRequest) (*GetEnabledWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnabledWallets not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) DisableWallet(context.Context, *DisableWalletRequest) (*DisableWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableWallet not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) DisableWallets(context.Context, *DisableWalletsRequest) (*DisableWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableWallets not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) EnableWallets(context.Context, *EnableWalletsRequest) (*EnableWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableWallets not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedHdWalletControllerManagerApiServer) mustEmbedUnimplementedHdWalletControllerManagerApiServer() {
}
func (UnimplementedHdWalletControllerManagerApiServer) testEmbeddedByValue() {}

// UnsafeHdWalletControllerManagerApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HdWalletControllerManagerApiServer will
// result in compilation errors.
type UnsafeHdWalletControllerManagerApiServer interface {
	mustEmbedUnimplementedHdWalletControllerManagerApiServer()
}

func RegisterHdWalletControllerManagerApiServer(s grpc.ServiceRegistrar, srv HdWalletControllerManagerApiServer) {
	// If the following call pancis, it indicates UnimplementedHdWalletControllerManagerApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HdWalletControllerManagerApi_ServiceDesc, srv)
}

func _HdWalletControllerManagerApi_AddNewWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).AddNewWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_AddNewWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).AddNewWallet(ctx, req.(*AddNewWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerManagerApi_ImportWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).ImportWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_ImportWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).ImportWallet(ctx, req.(*ImportWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerManagerApi_EnableWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).EnableWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_EnableWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).EnableWallet(ctx, req.(*EnableWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerManagerApi_GetWalletInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).GetWalletInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_GetWalletInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).GetWalletInfo(ctx, req.(*GetWalletInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerManagerApi_GetEnabledWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnabledWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).GetEnabledWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_GetEnabledWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).GetEnabledWallets(ctx, req.(*GetEnabledWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerManagerApi_DisableWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).DisableWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_DisableWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).DisableWallet(ctx, req.(*DisableWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerManagerApi_DisableWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).DisableWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_DisableWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).DisableWallets(ctx, req.(*DisableWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerManagerApi_EnableWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).EnableWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_EnableWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).EnableWallets(ctx, req.(*EnableWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerManagerApi_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerManagerApiServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerManagerApi_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerManagerApiServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HdWalletControllerManagerApi_ServiceDesc is the grpc.ServiceDesc for HdWalletControllerManagerApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HdWalletControllerManagerApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager_api.HdWalletControllerManagerApi",
	HandlerType: (*HdWalletControllerManagerApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNewWallet",
			Handler:    _HdWalletControllerManagerApi_AddNewWallet_Handler,
		},
		{
			MethodName: "ImportWallet",
			Handler:    _HdWalletControllerManagerApi_ImportWallet_Handler,
		},
		{
			MethodName: "EnableWallet",
			Handler:    _HdWalletControllerManagerApi_EnableWallet_Handler,
		},
		{
			MethodName: "GetWalletInfo",
			Handler:    _HdWalletControllerManagerApi_GetWalletInfo_Handler,
		},
		{
			MethodName: "GetEnabledWallets",
			Handler:    _HdWalletControllerManagerApi_GetEnabledWallets_Handler,
		},
		{
			MethodName: "DisableWallet",
			Handler:    _HdWalletControllerManagerApi_DisableWallet_Handler,
		},
		{
			MethodName: "DisableWallets",
			Handler:    _HdWalletControllerManagerApi_DisableWallets_Handler,
		},
		{
			MethodName: "EnableWallets",
			Handler:    _HdWalletControllerManagerApi_EnableWallets_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _HdWalletControllerManagerApi_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller_api.proto",
}

const (
	HdWalletControllerWalletApi_GetWalletInfo_FullMethodName        = "/manager_api.HdWalletControllerWalletApi/GetWalletInfo"
	HdWalletControllerWalletApi_StartWalletSession_FullMethodName   = "/manager_api.HdWalletControllerWalletApi/StartWalletSession"
	HdWalletControllerWalletApi_GetWalletSession_FullMethodName     = "/manager_api.HdWalletControllerWalletApi/GetWalletSession"
	HdWalletControllerWalletApi_GetAllWalletSessions_FullMethodName = "/manager_api.HdWalletControllerWalletApi/GetAllWalletSessions"
	HdWalletControllerWalletApi_CloseWalletSession_FullMethodName   = "/manager_api.HdWalletControllerWalletApi/CloseWalletSession"
	HdWalletControllerWalletApi_GetAccount_FullMethodName           = "/manager_api.HdWalletControllerWalletApi/GetAccount"
	HdWalletControllerWalletApi_GetMultipleAccounts_FullMethodName  = "/manager_api.HdWalletControllerWalletApi/GetMultipleAccounts"
	HdWalletControllerWalletApi_PrepareSignRequest_FullMethodName   = "/manager_api.HdWalletControllerWalletApi/PrepareSignRequest"
	HdWalletControllerWalletApi_ExecuteSignRequest_FullMethodName   = "/manager_api.HdWalletControllerWalletApi/ExecuteSignRequest"
)

// HdWalletControllerWalletApiClient is the client API for HdWalletControllerWalletApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HdWalletControllerWalletApiClient interface {
	GetWalletInfo(ctx context.Context, in *GetWalletInfoRequest, opts ...grpc.CallOption) (*GetWalletInfoResponse, error)
	StartWalletSession(ctx context.Context, in *StartWalletSessionRequest, opts ...grpc.CallOption) (*StartWalletSessionResponse, error)
	GetWalletSession(ctx context.Context, in *GetWalletSessionRequest, opts ...grpc.CallOption) (*GetWalletSessionResponse, error)
	GetAllWalletSessions(ctx context.Context, in *GetWalletSessionsRequest, opts ...grpc.CallOption) (*GetWalletSessionsResponse, error)
	CloseWalletSession(ctx context.Context, in *CloseWalletSessionsRequest, opts ...grpc.CallOption) (*CloseWalletSessionsResponse, error)
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	GetMultipleAccounts(ctx context.Context, in *GetMultipleAccountRequest, opts ...grpc.CallOption) (*GetMultipleAccountResponse, error)
	PrepareSignRequest(ctx context.Context, in *PrepareSignRequestReq, opts ...grpc.CallOption) (*PrepareSignRequestResponse, error)
	ExecuteSignRequest(ctx context.Context, in *ExecuteSignRequestReq, opts ...grpc.CallOption) (*ExecuteSignRequestResponse, error)
}

type hdWalletControllerWalletApiClient struct {
	cc grpc.ClientConnInterface
}

func NewHdWalletControllerWalletApiClient(cc grpc.ClientConnInterface) HdWalletControllerWalletApiClient {
	return &hdWalletControllerWalletApiClient{cc}
}

func (c *hdWalletControllerWalletApiClient) GetWalletInfo(ctx context.Context, in *GetWalletInfoRequest, opts ...grpc.CallOption) (*GetWalletInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletInfoResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_GetWalletInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerWalletApiClient) StartWalletSession(ctx context.Context, in *StartWalletSessionRequest, opts ...grpc.CallOption) (*StartWalletSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWalletSessionResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_StartWalletSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerWalletApiClient) GetWalletSession(ctx context.Context, in *GetWalletSessionRequest, opts ...grpc.CallOption) (*GetWalletSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletSessionResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_GetWalletSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerWalletApiClient) GetAllWalletSessions(ctx context.Context, in *GetWalletSessionsRequest, opts ...grpc.CallOption) (*GetWalletSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletSessionsResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_GetAllWalletSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerWalletApiClient) CloseWalletSession(ctx context.Context, in *CloseWalletSessionsRequest, opts ...grpc.CallOption) (*CloseWalletSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseWalletSessionsResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_CloseWalletSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerWalletApiClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerWalletApiClient) GetMultipleAccounts(ctx context.Context, in *GetMultipleAccountRequest, opts ...grpc.CallOption) (*GetMultipleAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMultipleAccountResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_GetMultipleAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerWalletApiClient) PrepareSignRequest(ctx context.Context, in *PrepareSignRequestReq, opts ...grpc.CallOption) (*PrepareSignRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareSignRequestResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_PrepareSignRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerWalletApiClient) ExecuteSignRequest(ctx context.Context, in *ExecuteSignRequestReq, opts ...grpc.CallOption) (*ExecuteSignRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteSignRequestResponse)
	err := c.cc.Invoke(ctx, HdWalletControllerWalletApi_ExecuteSignRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HdWalletControllerWalletApiServer is the server API for HdWalletControllerWalletApi service.
// All implementations must embed UnimplementedHdWalletControllerWalletApiServer
// for forward compatibility.
type HdWalletControllerWalletApiServer interface {
	GetWalletInfo(context.Context, *GetWalletInfoRequest) (*GetWalletInfoResponse, error)
	StartWalletSession(context.Context, *StartWalletSessionRequest) (*StartWalletSessionResponse, error)
	GetWalletSession(context.Context, *GetWalletSessionRequest) (*GetWalletSessionResponse, error)
	GetAllWalletSessions(context.Context, *GetWalletSessionsRequest) (*GetWalletSessionsResponse, error)
	CloseWalletSession(context.Context, *CloseWalletSessionsRequest) (*CloseWalletSessionsResponse, error)
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	GetMultipleAccounts(context.Context, *GetMultipleAccountRequest) (*GetMultipleAccountResponse, error)
	PrepareSignRequest(context.Context, *PrepareSignRequestReq) (*PrepareSignRequestResponse, error)
	ExecuteSignRequest(context.Context, *ExecuteSignRequestReq) (*ExecuteSignRequestResponse, error)
	mustEmbedUnimplementedHdWalletControllerWalletApiServer()
}

// UnimplementedHdWalletControllerWalletApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHdWalletControllerWalletApiServer struct{}

func (UnimplementedHdWalletControllerWalletApiServer) GetWalletInfo(context.Context, *GetWalletInfoRequest) (*GetWalletInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletInfo not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) StartWalletSession(context.Context, *StartWalletSessionRequest) (*StartWalletSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWalletSession not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) GetWalletSession(context.Context, *GetWalletSessionRequest) (*GetWalletSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletSession not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) GetAllWalletSessions(context.Context, *GetWalletSessionsRequest) (*GetWalletSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllWalletSessions not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) CloseWalletSession(context.Context, *CloseWalletSessionsRequest) (*CloseWalletSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseWalletSession not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) GetMultipleAccounts(context.Context, *GetMultipleAccountRequest) (*GetMultipleAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultipleAccounts not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) PrepareSignRequest(context.Context, *PrepareSignRequestReq) (*PrepareSignRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareSignRequest not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) ExecuteSignRequest(context.Context, *ExecuteSignRequestReq) (*ExecuteSignRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSignRequest not implemented")
}
func (UnimplementedHdWalletControllerWalletApiServer) mustEmbedUnimplementedHdWalletControllerWalletApiServer() {
}
func (UnimplementedHdWalletControllerWalletApiServer) testEmbeddedByValue() {}

// UnsafeHdWalletControllerWalletApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HdWalletControllerWalletApiServer will
// result in compilation errors.
type UnsafeHdWalletControllerWalletApiServer interface {
	mustEmbedUnimplementedHdWalletControllerWalletApiServer()
}

func RegisterHdWalletControllerWalletApiServer(s grpc.ServiceRegistrar, srv HdWalletControllerWalletApiServer) {
	// If the following call pancis, it indicates UnimplementedHdWalletControllerWalletApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HdWalletControllerWalletApi_ServiceDesc, srv)
}

func _HdWalletControllerWalletApi_GetWalletInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).GetWalletInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_GetWalletInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).GetWalletInfo(ctx, req.(*GetWalletInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerWalletApi_StartWalletSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWalletSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).StartWalletSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_StartWalletSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).StartWalletSession(ctx, req.(*StartWalletSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerWalletApi_GetWalletSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).GetWalletSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_GetWalletSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).GetWalletSession(ctx, req.(*GetWalletSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerWalletApi_GetAllWalletSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).GetAllWalletSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_GetAllWalletSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).GetAllWalletSessions(ctx, req.(*GetWalletSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerWalletApi_CloseWalletSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseWalletSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).CloseWalletSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_CloseWalletSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).CloseWalletSession(ctx, req.(*CloseWalletSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerWalletApi_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerWalletApi_GetMultipleAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).GetMultipleAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_GetMultipleAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).GetMultipleAccounts(ctx, req.(*GetMultipleAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerWalletApi_PrepareSignRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSignRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).PrepareSignRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_PrepareSignRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).PrepareSignRequest(ctx, req.(*PrepareSignRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerWalletApi_ExecuteSignRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSignRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerWalletApiServer).ExecuteSignRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HdWalletControllerWalletApi_ExecuteSignRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerWalletApiServer).ExecuteSignRequest(ctx, req.(*ExecuteSignRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HdWalletControllerWalletApi_ServiceDesc is the grpc.ServiceDesc for HdWalletControllerWalletApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HdWalletControllerWalletApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager_api.HdWalletControllerWalletApi",
	HandlerType: (*HdWalletControllerWalletApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWalletInfo",
			Handler:    _HdWalletControllerWalletApi_GetWalletInfo_Handler,
		},
		{
			MethodName: "StartWalletSession",
			Handler:    _HdWalletControllerWalletApi_StartWalletSession_Handler,
		},
		{
			MethodName: "GetWalletSession",
			Handler:    _HdWalletControllerWalletApi_GetWalletSession_Handler,
		},
		{
			MethodName: "GetAllWalletSessions",
			Handler:    _HdWalletControllerWalletApi_GetAllWalletSessions_Handler,
		},
		{
			MethodName: "CloseWalletSession",
			Handler:    _HdWalletControllerWalletApi_CloseWalletSession_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _HdWalletControllerWalletApi_GetAccount_Handler,
		},
		{
			MethodName: "GetMultipleAccounts",
			Handler:    _HdWalletControllerWalletApi_GetMultipleAccounts_Handler,
		},
		{
			MethodName: "PrepareSignRequest",
			Handler:    _HdWalletControllerWalletApi_PrepareSignRequest_Handler,
		},
		{
			MethodName: "ExecuteSignRequest",
			Handler:    _HdWalletControllerWalletApi_ExecuteSignRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller_api.proto",
}
