// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package controller

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HdWalletControllerApiClient is the client API for HdWalletControllerApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HdWalletControllerApiClient interface {
	AddNewWallet(ctx context.Context, in *AddNewWalletRequest, opts ...grpc.CallOption) (*AddNewWalletResponse, error)
	ImportWallet(ctx context.Context, in *ImportWalletRequest, opts ...grpc.CallOption) (*ImportWalletResponse, error)
	EnableWallet(ctx context.Context, in *EnableWalletRequest, opts ...grpc.CallOption) (*EnableWalletResponse, error)
	GetWalletInfo(ctx context.Context, in *GetWalletInfoRequest, opts ...grpc.CallOption) (*GetWalletInfoResponse, error)
	GetEnabledWallets(ctx context.Context, in *GetEnabledWalletsRequest, opts ...grpc.CallOption) (*GetEnabledWalletsResponse, error)
	DisableWallet(ctx context.Context, in *DisableWalletRequest, opts ...grpc.CallOption) (*DisableWalletResponse, error)
	DisableWallets(ctx context.Context, in *DisableWalletsRequest, opts ...grpc.CallOption) (*DisableWalletsResponse, error)
	StartWalletSession(ctx context.Context, in *StartWalletSessionRequest, opts ...grpc.CallOption) (*StartWalletSessionResponse, error)
	GetWalletSession(ctx context.Context, in *GetWalletSessionRequest, opts ...grpc.CallOption) (*GetWalletSessionResponse, error)
	GetAllWalletSessions(ctx context.Context, in *GetWalletSessionsRequest, opts ...grpc.CallOption) (*GetWalletSessionsResponse, error)
	CloseWalletSession(ctx context.Context, in *CloseWalletSessionsRequest, opts ...grpc.CallOption) (*CloseWalletSessionsResponse, error)
	GetDerivationAddress(ctx context.Context, in *DerivationAddressRequest, opts ...grpc.CallOption) (*DerivationAddressResponse, error)
	GetDerivationAddressByRange(ctx context.Context, in *DerivationAddressByRangeRequest, opts ...grpc.CallOption) (*DerivationAddressByRangeResponse, error)
	PrepareSignRequest(ctx context.Context, in *PrepareSignRequestReq, opts ...grpc.CallOption) (*PrepareSignRequestResponse, error)
	ExecuteSignRequest(ctx context.Context, in *ExecuteSignRequestReq, opts ...grpc.CallOption) (*ExecuteSignRequestResponse, error)
}

type hdWalletControllerApiClient struct {
	cc grpc.ClientConnInterface
}

func NewHdWalletControllerApiClient(cc grpc.ClientConnInterface) HdWalletControllerApiClient {
	return &hdWalletControllerApiClient{cc}
}

func (c *hdWalletControllerApiClient) AddNewWallet(ctx context.Context, in *AddNewWalletRequest, opts ...grpc.CallOption) (*AddNewWalletResponse, error) {
	out := new(AddNewWalletResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/AddNewWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) ImportWallet(ctx context.Context, in *ImportWalletRequest, opts ...grpc.CallOption) (*ImportWalletResponse, error) {
	out := new(ImportWalletResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/ImportWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) EnableWallet(ctx context.Context, in *EnableWalletRequest, opts ...grpc.CallOption) (*EnableWalletResponse, error) {
	out := new(EnableWalletResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/EnableWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) GetWalletInfo(ctx context.Context, in *GetWalletInfoRequest, opts ...grpc.CallOption) (*GetWalletInfoResponse, error) {
	out := new(GetWalletInfoResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/GetWalletInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) GetEnabledWallets(ctx context.Context, in *GetEnabledWalletsRequest, opts ...grpc.CallOption) (*GetEnabledWalletsResponse, error) {
	out := new(GetEnabledWalletsResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/GetEnabledWallets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) DisableWallet(ctx context.Context, in *DisableWalletRequest, opts ...grpc.CallOption) (*DisableWalletResponse, error) {
	out := new(DisableWalletResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/DisableWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) DisableWallets(ctx context.Context, in *DisableWalletsRequest, opts ...grpc.CallOption) (*DisableWalletsResponse, error) {
	out := new(DisableWalletsResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/DisableWallets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) StartWalletSession(ctx context.Context, in *StartWalletSessionRequest, opts ...grpc.CallOption) (*StartWalletSessionResponse, error) {
	out := new(StartWalletSessionResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/StartWalletSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) GetWalletSession(ctx context.Context, in *GetWalletSessionRequest, opts ...grpc.CallOption) (*GetWalletSessionResponse, error) {
	out := new(GetWalletSessionResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/GetWalletSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) GetAllWalletSessions(ctx context.Context, in *GetWalletSessionsRequest, opts ...grpc.CallOption) (*GetWalletSessionsResponse, error) {
	out := new(GetWalletSessionsResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/GetAllWalletSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) CloseWalletSession(ctx context.Context, in *CloseWalletSessionsRequest, opts ...grpc.CallOption) (*CloseWalletSessionsResponse, error) {
	out := new(CloseWalletSessionsResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/CloseWalletSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) GetDerivationAddress(ctx context.Context, in *DerivationAddressRequest, opts ...grpc.CallOption) (*DerivationAddressResponse, error) {
	out := new(DerivationAddressResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/GetDerivationAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) GetDerivationAddressByRange(ctx context.Context, in *DerivationAddressByRangeRequest, opts ...grpc.CallOption) (*DerivationAddressByRangeResponse, error) {
	out := new(DerivationAddressByRangeResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/GetDerivationAddressByRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) PrepareSignRequest(ctx context.Context, in *PrepareSignRequestReq, opts ...grpc.CallOption) (*PrepareSignRequestResponse, error) {
	out := new(PrepareSignRequestResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/PrepareSignRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hdWalletControllerApiClient) ExecuteSignRequest(ctx context.Context, in *ExecuteSignRequestReq, opts ...grpc.CallOption) (*ExecuteSignRequestResponse, error) {
	out := new(ExecuteSignRequestResponse)
	err := c.cc.Invoke(ctx, "/manager_api.HdWalletControllerApi/ExecuteSignRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HdWalletControllerApiServer is the server API for HdWalletControllerApi service.
// All implementations must embed UnimplementedHdWalletControllerApiServer
// for forward compatibility
type HdWalletControllerApiServer interface {
	AddNewWallet(context.Context, *AddNewWalletRequest) (*AddNewWalletResponse, error)
	ImportWallet(context.Context, *ImportWalletRequest) (*ImportWalletResponse, error)
	EnableWallet(context.Context, *EnableWalletRequest) (*EnableWalletResponse, error)
	GetWalletInfo(context.Context, *GetWalletInfoRequest) (*GetWalletInfoResponse, error)
	GetEnabledWallets(context.Context, *GetEnabledWalletsRequest) (*GetEnabledWalletsResponse, error)
	DisableWallet(context.Context, *DisableWalletRequest) (*DisableWalletResponse, error)
	DisableWallets(context.Context, *DisableWalletsRequest) (*DisableWalletsResponse, error)
	StartWalletSession(context.Context, *StartWalletSessionRequest) (*StartWalletSessionResponse, error)
	GetWalletSession(context.Context, *GetWalletSessionRequest) (*GetWalletSessionResponse, error)
	GetAllWalletSessions(context.Context, *GetWalletSessionsRequest) (*GetWalletSessionsResponse, error)
	CloseWalletSession(context.Context, *CloseWalletSessionsRequest) (*CloseWalletSessionsResponse, error)
	GetDerivationAddress(context.Context, *DerivationAddressRequest) (*DerivationAddressResponse, error)
	GetDerivationAddressByRange(context.Context, *DerivationAddressByRangeRequest) (*DerivationAddressByRangeResponse, error)
	PrepareSignRequest(context.Context, *PrepareSignRequestReq) (*PrepareSignRequestResponse, error)
	ExecuteSignRequest(context.Context, *ExecuteSignRequestReq) (*ExecuteSignRequestResponse, error)
	mustEmbedUnimplementedHdWalletControllerApiServer()
}

// UnimplementedHdWalletControllerApiServer must be embedded to have forward compatible implementations.
type UnimplementedHdWalletControllerApiServer struct {
}

func (UnimplementedHdWalletControllerApiServer) AddNewWallet(context.Context, *AddNewWalletRequest) (*AddNewWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNewWallet not implemented")
}
func (UnimplementedHdWalletControllerApiServer) ImportWallet(context.Context, *ImportWalletRequest) (*ImportWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportWallet not implemented")
}
func (UnimplementedHdWalletControllerApiServer) EnableWallet(context.Context, *EnableWalletRequest) (*EnableWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableWallet not implemented")
}
func (UnimplementedHdWalletControllerApiServer) GetWalletInfo(context.Context, *GetWalletInfoRequest) (*GetWalletInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletInfo not implemented")
}
func (UnimplementedHdWalletControllerApiServer) GetEnabledWallets(context.Context, *GetEnabledWalletsRequest) (*GetEnabledWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEnabledWallets not implemented")
}
func (UnimplementedHdWalletControllerApiServer) DisableWallet(context.Context, *DisableWalletRequest) (*DisableWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableWallet not implemented")
}
func (UnimplementedHdWalletControllerApiServer) DisableWallets(context.Context, *DisableWalletsRequest) (*DisableWalletsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableWallets not implemented")
}
func (UnimplementedHdWalletControllerApiServer) StartWalletSession(context.Context, *StartWalletSessionRequest) (*StartWalletSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartWalletSession not implemented")
}
func (UnimplementedHdWalletControllerApiServer) GetWalletSession(context.Context, *GetWalletSessionRequest) (*GetWalletSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWalletSession not implemented")
}
func (UnimplementedHdWalletControllerApiServer) GetAllWalletSessions(context.Context, *GetWalletSessionsRequest) (*GetWalletSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllWalletSessions not implemented")
}
func (UnimplementedHdWalletControllerApiServer) CloseWalletSession(context.Context, *CloseWalletSessionsRequest) (*CloseWalletSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseWalletSession not implemented")
}
func (UnimplementedHdWalletControllerApiServer) GetDerivationAddress(context.Context, *DerivationAddressRequest) (*DerivationAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDerivationAddress not implemented")
}
func (UnimplementedHdWalletControllerApiServer) GetDerivationAddressByRange(context.Context, *DerivationAddressByRangeRequest) (*DerivationAddressByRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDerivationAddressByRange not implemented")
}
func (UnimplementedHdWalletControllerApiServer) PrepareSignRequest(context.Context, *PrepareSignRequestReq) (*PrepareSignRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareSignRequest not implemented")
}
func (UnimplementedHdWalletControllerApiServer) ExecuteSignRequest(context.Context, *ExecuteSignRequestReq) (*ExecuteSignRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteSignRequest not implemented")
}
func (UnimplementedHdWalletControllerApiServer) mustEmbedUnimplementedHdWalletControllerApiServer() {}

// UnsafeHdWalletControllerApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HdWalletControllerApiServer will
// result in compilation errors.
type UnsafeHdWalletControllerApiServer interface {
	mustEmbedUnimplementedHdWalletControllerApiServer()
}

func RegisterHdWalletControllerApiServer(s grpc.ServiceRegistrar, srv HdWalletControllerApiServer) {
	s.RegisterService(&HdWalletControllerApi_ServiceDesc, srv)
}

func _HdWalletControllerApi_AddNewWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNewWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).AddNewWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/AddNewWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).AddNewWallet(ctx, req.(*AddNewWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_ImportWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).ImportWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/ImportWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).ImportWallet(ctx, req.(*ImportWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_EnableWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).EnableWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/EnableWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).EnableWallet(ctx, req.(*EnableWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_GetWalletInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).GetWalletInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/GetWalletInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).GetWalletInfo(ctx, req.(*GetWalletInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_GetEnabledWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEnabledWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).GetEnabledWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/GetEnabledWallets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).GetEnabledWallets(ctx, req.(*GetEnabledWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_DisableWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).DisableWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/DisableWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).DisableWallet(ctx, req.(*DisableWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_DisableWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).DisableWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/DisableWallets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).DisableWallets(ctx, req.(*DisableWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_StartWalletSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWalletSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).StartWalletSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/StartWalletSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).StartWalletSession(ctx, req.(*StartWalletSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_GetWalletSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).GetWalletSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/GetWalletSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).GetWalletSession(ctx, req.(*GetWalletSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_GetAllWalletSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).GetAllWalletSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/GetAllWalletSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).GetAllWalletSessions(ctx, req.(*GetWalletSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_CloseWalletSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseWalletSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).CloseWalletSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/CloseWalletSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).CloseWalletSession(ctx, req.(*CloseWalletSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_GetDerivationAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DerivationAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).GetDerivationAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/GetDerivationAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).GetDerivationAddress(ctx, req.(*DerivationAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_GetDerivationAddressByRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DerivationAddressByRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).GetDerivationAddressByRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/GetDerivationAddressByRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).GetDerivationAddressByRange(ctx, req.(*DerivationAddressByRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_PrepareSignRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareSignRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).PrepareSignRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/PrepareSignRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).PrepareSignRequest(ctx, req.(*PrepareSignRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HdWalletControllerApi_ExecuteSignRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteSignRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HdWalletControllerApiServer).ExecuteSignRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/manager_api.HdWalletControllerApi/ExecuteSignRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HdWalletControllerApiServer).ExecuteSignRequest(ctx, req.(*ExecuteSignRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

// HdWalletControllerApi_ServiceDesc is the grpc.ServiceDesc for HdWalletControllerApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HdWalletControllerApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "manager_api.HdWalletControllerApi",
	HandlerType: (*HdWalletControllerApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNewWallet",
			Handler:    _HdWalletControllerApi_AddNewWallet_Handler,
		},
		{
			MethodName: "ImportWallet",
			Handler:    _HdWalletControllerApi_ImportWallet_Handler,
		},
		{
			MethodName: "EnableWallet",
			Handler:    _HdWalletControllerApi_EnableWallet_Handler,
		},
		{
			MethodName: "GetWalletInfo",
			Handler:    _HdWalletControllerApi_GetWalletInfo_Handler,
		},
		{
			MethodName: "GetEnabledWallets",
			Handler:    _HdWalletControllerApi_GetEnabledWallets_Handler,
		},
		{
			MethodName: "DisableWallet",
			Handler:    _HdWalletControllerApi_DisableWallet_Handler,
		},
		{
			MethodName: "DisableWallets",
			Handler:    _HdWalletControllerApi_DisableWallets_Handler,
		},
		{
			MethodName: "StartWalletSession",
			Handler:    _HdWalletControllerApi_StartWalletSession_Handler,
		},
		{
			MethodName: "GetWalletSession",
			Handler:    _HdWalletControllerApi_GetWalletSession_Handler,
		},
		{
			MethodName: "GetAllWalletSessions",
			Handler:    _HdWalletControllerApi_GetAllWalletSessions_Handler,
		},
		{
			MethodName: "CloseWalletSession",
			Handler:    _HdWalletControllerApi_CloseWalletSession_Handler,
		},
		{
			MethodName: "GetDerivationAddress",
			Handler:    _HdWalletControllerApi_GetDerivationAddress_Handler,
		},
		{
			MethodName: "GetDerivationAddressByRange",
			Handler:    _HdWalletControllerApi_GetDerivationAddressByRange_Handler,
		},
		{
			MethodName: "PrepareSignRequest",
			Handler:    _HdWalletControllerApi_PrepareSignRequest_Handler,
		},
		{
			MethodName: "ExecuteSignRequest",
			Handler:    _HdWalletControllerApi_ExecuteSignRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controller_api.proto",
}
