// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson410336b1DecodeGithubComCryptoBundleBcWalletCommonHdwalletControllerInternalEntities(in *jlexer.Lexer, out *AccessTokenWalletSession) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "token_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.AccessTokeUUID).UnmarshalText(data))
			}
		case "wallet_session_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.SessionUUID).UnmarshalText(data))
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson410336b1EncodeGithubComCryptoBundleBcWalletCommonHdwalletControllerInternalEntities(out *jwriter.Writer, in AccessTokenWalletSession) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"token_uuid\":"
		out.RawString(prefix[1:])
		out.RawText((in.AccessTokeUUID).MarshalText())
	}
	{
		const prefix string = ",\"wallet_session_uuid\":"
		out.RawString(prefix)
		out.RawText((in.SessionUUID).MarshalText())
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AccessTokenWalletSession) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson410336b1EncodeGithubComCryptoBundleBcWalletCommonHdwalletControllerInternalEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AccessTokenWalletSession) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson410336b1EncodeGithubComCryptoBundleBcWalletCommonHdwalletControllerInternalEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AccessTokenWalletSession) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson410336b1DecodeGithubComCryptoBundleBcWalletCommonHdwalletControllerInternalEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AccessTokenWalletSession) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson410336b1DecodeGithubComCryptoBundleBcWalletCommonHdwalletControllerInternalEntities(l, v)
}
