// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package entities

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
	time "time"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson842a094aDecodeGitlabHeronodesIoBcPlatformBcWalletTronHdwalletInternalEntities(in *jlexer.Lexer, out *MnemonicWallet) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint32(in.Uint32())
		case "uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.UUID).UnmarshalText(data))
			}
		case "wallet_uuid":
			if data := in.UnsafeBytes(); in.Ok() {
				in.AddError((out.WalletUUID).UnmarshalText(data))
			}
		case "mnemonic_hash":
			out.MnemonicHash = string(in.String())
		case "is_hot":
			out.IsHotWallet = bool(in.Bool())
		case "unload_interval":
			out.UnloadInterval = time.Duration(in.Int64())
		case "rsa_encrypted":
			if in.IsNull() {
				in.Skip()
				out.RsaEncrypted = nil
			} else {
				out.RsaEncrypted = in.Bytes()
			}
		case "rsa_encrypted_hash":
			out.RsaEncryptedHash = string(in.String())
		case "vault_encrypted":
			if in.IsNull() {
				in.Skip()
				out.VaultEncrypted = nil
			} else {
				out.VaultEncrypted = in.Bytes()
			}
		case "vault_encrypted_hash":
			out.VaultEncryptedHash = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if in.IsNull() {
				in.Skip()
				out.UpdatedAt = nil
			} else {
				if out.UpdatedAt == nil {
					out.UpdatedAt = new(time.Time)
				}
				if data := in.Raw(); in.Ok() {
					in.AddError((*out.UpdatedAt).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson842a094aEncodeGitlabHeronodesIoBcPlatformBcWalletTronHdwalletInternalEntities(out *jwriter.Writer, in MnemonicWallet) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.ID))
	}
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix)
		out.RawText((in.UUID).MarshalText())
	}
	{
		const prefix string = ",\"wallet_uuid\":"
		out.RawString(prefix)
		out.RawText((in.WalletUUID).MarshalText())
	}
	{
		const prefix string = ",\"mnemonic_hash\":"
		out.RawString(prefix)
		out.String(string(in.MnemonicHash))
	}
	{
		const prefix string = ",\"is_hot\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsHotWallet))
	}
	{
		const prefix string = ",\"unload_interval\":"
		out.RawString(prefix)
		out.Int64(int64(in.UnloadInterval))
	}
	{
		const prefix string = ",\"rsa_encrypted\":"
		out.RawString(prefix)
		out.Base64Bytes(in.RsaEncrypted)
	}
	{
		const prefix string = ",\"rsa_encrypted_hash\":"
		out.RawString(prefix)
		out.String(string(in.RsaEncryptedHash))
	}
	{
		const prefix string = ",\"vault_encrypted\":"
		out.RawString(prefix)
		out.Base64Bytes(in.VaultEncrypted)
	}
	{
		const prefix string = ",\"vault_encrypted_hash\":"
		out.RawString(prefix)
		out.String(string(in.VaultEncryptedHash))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		if in.UpdatedAt == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.UpdatedAt).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MnemonicWallet) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson842a094aEncodeGitlabHeronodesIoBcPlatformBcWalletTronHdwalletInternalEntities(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MnemonicWallet) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson842a094aEncodeGitlabHeronodesIoBcPlatformBcWalletTronHdwalletInternalEntities(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MnemonicWallet) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson842a094aDecodeGitlabHeronodesIoBcPlatformBcWalletTronHdwalletInternalEntities(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MnemonicWallet) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson842a094aDecodeGitlabHeronodesIoBcPlatformBcWalletTronHdwalletInternalEntities(l, v)
}
